/**
 * 
 */
package cn.aposoft.wechat.access;

import java.util.Date;

import cn.aposoft.wechat.account.AccountType;

/**
 * @author Jann Liu
 * @since 1.0
 */
public class AccessTokenStore implements CompanyAccessTokenStore {
	private static final long serialVersionUID = -7687619155566052350L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.account_type
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private AccountType accountType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.id
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.agent_id
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private Integer agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private String access_token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.expires_in
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private int expires_in;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column access_token.refresh_time
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	private Date refreshTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.account_type
	 * 
	 * @return the value of access_token.account_type
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public AccountType getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.account_type
	 * 
	 * @param accountType
	 *            the value for access_token.account_type
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setAccountType(AccountType accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.id
	 * 
	 * @return the value of access_token.id
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.id
	 * 
	 * @param id
	 *            the value for access_token.id
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.agent_id
	 * 
	 * @return the value of access_token.agent_id
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public Integer getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.agent_id
	 * 
	 * @param agentId
	 *            the value for access_token.agent_id
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.access_token
	 * 
	 * @return the value of access_token.access_token
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public String getAccess_token() {
		return access_token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.access_token
	 * 
	 * @param access_token
	 *            the value for access_token.access_token
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setAccess_token(String access_token) {
		this.access_token = access_token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.expires_in
	 * 
	 * @return the value of access_token.expires_in
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public int getExpires_in() {
		return expires_in;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.expires_in
	 * 
	 * @param expires_in
	 *            the value for access_token.expires_in
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setExpires_in(int expires_in) {
		this.expires_in = expires_in;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column access_token.refresh_time
	 * 
	 * @return the value of access_token.refresh_time
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public Date getRefreshTime() {
		return refreshTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column access_token.refresh_time
	 * 
	 * @param refreshTime
	 *            the value for access_token.refresh_time
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	public void setRefreshTime(Date refreshTime) {
		this.refreshTime = refreshTime;
	}

}
