# server infomation
server:
  port: 8080
  contextPath: /wx

# datasource
spring:
  datasource:
    name: wechat_dev
    url: jdbc:mysql://localhost:3306/wechat_dev?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: wechat_test
    password: wechat_test
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 200
mybatis: 
  mapperLocations: classpath*:mybatis/*Mapper.xml
  executorType: REUSE
#  typeAliasesPackage: tk.mapper.model

#   mybatis.config：mybatis-config.xml配置文件的路径
#   mybatis.typeHandlersPackage：扫描typeHandlers的包
#   mybatis.checkConfigLocation：检查配置文件是否存在
#   mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
