package cn.aposoft.wechat.config.repo;

import cn.aposoft.wechat.config.repo.AccountConfig;
import cn.aposoft.wechat.config.repo.AccountConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    long countByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    int deleteByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    int insert(AccountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    int insertSelective(AccountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    List<AccountConfig> selectByExample(AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_config
     *
     * @mbg.generated Mon Jun 26 09:53:19 CST 2017
     */
    int updateByExample(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);
}