package cn.aposoft.wechat.config.repo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.aposoft.wechat.config.WechatCompanyConfig;
import cn.aposoft.wechat.config.WechatMpConfig;

public interface AccountConfigMapper {
	/**
	 * 新增或更新DbAccountConfig记录
	 * 
	 * @param record
	 *            新增,当遇到相同KEY时,更新原有记录
	 * @return 影响记录行数
	 */
	int setMp(WechatMpConfig record);

	/**
	 * 新增或更新DbAccountConfig记录
	 * 
	 * @param record
	 *            新增,当遇到相同KEY时,更新原有记录
	 * @return 影响记录行数
	 */
	int setCorp(WechatCompanyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	long countByExample(AccountConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	int deleteByExample(AccountConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	int insert(AccountConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	int insertSelective(AccountConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	List<AccountConfig> selectByExample(AccountConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account_config
	 *
	 * @mbg.generated Mon Jun 26 09:53:19 CST 2017
	 */
	int updateByExample(@Param("record") AccountConfig record, @Param("example") AccountConfigExample example);
}