package cn.aposoft.wechat.access.db.mybatis;

import cn.aposoft.wechat.access.db.mybatis.DbAccessConfig;
import cn.aposoft.wechat.access.db.mybatis.DbAccessConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbAccessConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    long countByExample(DbAccessConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int deleteByExample(DbAccessConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int insert(DbAccessConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int insertSelective(DbAccessConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    List<DbAccessConfig> selectByExample(DbAccessConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") DbAccessConfig record, @Param("example") DbAccessConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_config
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int updateByExample(@Param("record") DbAccessConfig record, @Param("example") DbAccessConfigExample example);
}