package cn.aposoft.wechat.access.db.mybatis;

import java.util.Date;

public class DbAccessConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.account_type
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.agent_id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private Integer agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.access_token_secret
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.aes_key
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private String aesKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.callback_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_config.create_time
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.account_type
     *
     * @return the value of access_config.account_type
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.account_type
     *
     * @param accountType the value for access_config.account_type
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.id
     *
     * @return the value of access_config.id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.id
     *
     * @param id the value for access_config.id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.agent_id
     *
     * @return the value of access_config.agent_id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.agent_id
     *
     * @param agentId the value for access_config.agent_id
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.access_token_secret
     *
     * @return the value of access_config.access_token_secret
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.access_token_secret
     *
     * @param secret the value for access_config.access_token_secret
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.aes_key
     *
     * @return the value of access_config.aes_key
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public String getAesKey() {
        return aesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.aes_key
     *
     * @param aesKey the value for access_config.aes_key
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setAesKey(String aesKey) {
        this.aesKey = aesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.callback_token
     *
     * @return the value of access_config.callback_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.callback_token
     *
     * @param token the value for access_config.callback_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_config.create_time
     *
     * @return the value of access_config.create_time
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_config.create_time
     *
     * @param createTime the value for access_config.create_time
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}