package cn.aposoft.wechat.access.db.mybatis;

import cn.aposoft.wechat.access.db.mybatis.DbAccessToken;
import cn.aposoft.wechat.access.db.mybatis.DbAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    long countByExample(DbAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int deleteByExample(DbAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int insert(DbAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int insertSelective(DbAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    List<DbAccessToken> selectByExample(DbAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") DbAccessToken record, @Param("example") DbAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Fri Jun 02 18:45:14 CST 2017
     */
    int updateByExample(@Param("record") DbAccessToken record, @Param("example") DbAccessTokenExample example);
}