package cn.aposoft.wechat.access.repo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.aposoft.wechat.access.CompanyAccessTokenStore;
import cn.aposoft.wechat.access.MpAccessTokenStore;

/**
 * AccessToken 的数据库访问支持
 * 
 * @author Jann Liu
 * @since 1.0
 */
public interface DbAccessTokenMapper {
	/**
	 * 如果token存在,则更新,如果不存在,则新增
	 * 
	 * @param tokenStore
	 *            公众号,服务号Token保存
	 * @return 保存影像数量
	 */
	int setMpAccessToken(MpAccessTokenStore tokenStore);

	/**
	 * 保存企业号的Token信息
	 * 
	 * @param tokenStore
	 *            token的存储信息
	 * @return 返回影响数据库行数
	 */
	int setCompanyAccessToken(CompanyAccessTokenStore tokenStore);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	long countByExample(DbAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	int deleteByExample(DbAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	int insert(DbAccessToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	int insertSelective(DbAccessToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	List<DbAccessToken> selectByExample(DbAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DbAccessToken record, @Param("example") DbAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table access_token
	 * 
	 * @mbg.generated Tue Jun 27 16:57:40 CST 2017
	 */
	int updateByExample(@Param("record") DbAccessToken record, @Param("example") DbAccessTokenExample example);

}